language: node_js
node_js:
  - "8"

env:
  global:
    # npm
    - secure: "UwWNdlpCWvXiN9qvyFwQYgJMOb+pSBgPNoxMHo8J/eWhTs7Glu+hTyHdDw/DR/zjayLghKDkEK703lGtGKI8MiTWuZc2lCPqeSdetX8RnmUXeJfWbCP5ES7zXXhJ24Y9KKKUXQuDJO26ZkZu1LSv9ifFalsRqAdnRzfjbSgpZq9X+nz/xOMrZY8rXozUCxCT94NkWoS1WlMyab90oWJ2lBlO7NwtDM1QhL28g/R2FQIwxUyqFljyKEELKCFnoekb1Ait4WrgS+PmQZWgqBghpa/g/li8ZJGlGsI2jwuxSpt+4uzU/3AkyZMCv6ryXntJKAli18708LKWexBMPX4zmnB+20aEblwqza3GduCtHttcFNaNYIYIsfefM/eKU/pEhSXWH4wN9YMF3j/aZ2vYE46X/BP1BVJCxuMGOjDHcEMaUHhLjTx7hx/xChWG0VvyHlHPZGccVNo/8q7jupA+APsrZJIgv9DeQ93pC3H5YpBulHso8cpB5cqb6n5yewOLBxNLY6Av42wNAuPLJ69wCTr8+RigxwgthP4kiyVsGffdkUd6Dl15OZ7hzqHmfk1f6shsDQwevhTgebYf6d0QtEijqfnX3Rjvu89PjFW7yg+lV/CDyqeFWrcMWHaiFanox1d8O7bDQrq6Hm5rinWkizO5WwzAmhWNSuAFi/RqUV8="
    # github
    # - secure: "J+1oWjvvXjyrwkY/4IFWKdN/weFmQcPwlRuFG4R0Gb3rYe4nqtC9l68sJvmS8asc8dQMhOhcUZCH6sjvo7l2WD4NuK4umPSbs+rJNUsfbvH4pZjStQIj/3ll1OfQelGDWAYQWhIfciYY4F3Bp0ZWTfKOppLQ2AVIYu1fPVXDdlo="
    # github changelog
    # - secure: "KcGydAqL7ryDh2rTJJB4wU8NE5BRtnrRXDEcPBScSscO3zFsHXHBDvvO04B/9hFVatXzGYXmkn+FZ0P9QikhvebzdwwyqUG2SKFiHhMvbX0m0WtAhn5NqDuKU1r5qy5YQ18r/tiLfC9GSAlEpfLAH58pwpcn8srV3Mn/yKvlrfs="


deploy:
  provider: script
  script: scripts/release.sh
  skip_cleanup: true
  on:
    repo: Parity-JS/parity-react-app
    tags: false
