language: node_js
node_js:
  - "8"

env:
  global:
    # npm
    - secure: "mLxQhdDSP9Uy8Vu+tS+1fEAOePEVMDb9M55osq0wv/wRS0M2VHh9hwMuFe4c2Gx6LSGZkQqF5BH1uMySyNx0bulcHpZ5CMSrm0PEvNp/vOHuaFTebZfG0sx7m/2jKkB4gscK0p7sNFjixFLSAz9OWOllpEkQLmCTDQKxOUErWA8Y5W7jbJgX/tVBotp4lkYseH9R5bvcRJT3ULIdwg5fB5JsOeD2SpyM/uwSUqdoU6womCpTap0+c5SKDQfDKtD7ngFYhNq7SE2eBEM8WE7i/XTooVKDEQUrLgPdCS0WC2nuhu3gMyImMczaxoCnpQjUuN/RjTiSEqb4Cu2KvqsD8oLOk21KS72r1T/t3N5F019/1c1MQ74p6kQSZsjZS9T2dc1X47CP8q4+XWp68Im1Bj2VRx4JUt/+lhbxwYffqZQf/8bh/Bf9ipVsHXUJJ9hhR+/0NzMuCL7V8uvO40xhwqZofDuB+K30y0faL1C74J1EhvQM/V5fK/wP2F1QcWFgbND0gkvjHj2eQoEf7nMn8GzwcY9Mw8I0bsiQRCsP5t1aeoaZW42hBeRxykX5HAafOmJSXwJ43bWMbgDl+LF6GfMm/lOHIYFRoPdXrgAlxo/8nizGBp7/ZOBWNaf9VMBAEhmMZkL7RiVj1BUBUr6R79Iyfy/5/4J2OE/7IBXukVA="
    # github
    - secure: "jgRr9EXW7J6EC+ZNIMmdSA2NT8y/qUQ0BeaW7BElLdMve481Zmi4aUQXmzP8dgnYrpQcL7g/YeVJYM2BgGG/fplnf4zj6BKl9bwtyJ3pfWnx1NvduJkEsc19ptvYYX+E5FYHwap0YUEv+HKJRDF2e7JXmqatI6W6jvuy/mTYyua1OxD/N8OGNFxuas2GOE4ZUDTBIAVaeept5ZY/td5eEb2vwUht6B5FBf/pZdz5GMXFWzccZweIUZqzSxoWuTVugIohqSzQ7y9SHCEJpshrTIL4c8fd2gjAVK4ULmuw0r2RgEzTvBKbWAoOfbHvCyPiu18FBj1IYtQcGP73GGaR6R7AIaGVEhnXoSE6Qwg6oC7x9NVDdrlG5IpXCmotrI3m/49b93MTJd34MsjblFCel2tbg7JAyhkRHLwEcjTU13skVyPRovYXBszxSzFZwcUBvF4HMSj9KFNq7ZVcK9ZrpQ5RR3mxBPU77E3C72SSA+jrt2xIAfIrNz2FHokX4y/kUoYKGhW22LElhPGwJRwUjSDwqhSZg03xDSApmIvZ3eeoesEpxTftgo1LYlCNIbFSHYEHrbDGQ80nhcCuCz6doDYZWmvFgmFEnQzkJZ3DexKcGhCWFyAgI3GrEscUolfYghk45X9iLuaDLSyxYOZaZiQpS1lcAhGvD33yR3cMudI="
    # github changelog
    # - secure: "KcGydAqL7ryDh2rTJJB4wU8NE5BRtnrRXDEcPBScSscO3zFsHXHBDvvO04B/9hFVatXzGYXmkn+FZ0P9QikhvebzdwwyqUG2SKFiHhMvbX0m0WtAhn5NqDuKU1r5qy5YQ18r/tiLfC9GSAlEpfLAH58pwpcn8srV3Mn/yKvlrfs="

after_success:
  # this will short-circuit the publish step if it fails to interpolate $NPM_API_KEY
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"

deploy:
  provider: script
  script: scripts/release.sh
  skip_cleanup: true
  on:
    repo: Parity-JS/parity-react-app
    tags: false
