language: node_js
node_js:
  - "8"

env:
  global:
    # npm
    - secure: "mLxQhdDSP9Uy8Vu+tS+1fEAOePEVMDb9M55osq0wv/wRS0M2VHh9hwMuFe4c2Gx6LSGZkQqF5BH1uMySyNx0bulcHpZ5CMSrm0PEvNp/vOHuaFTebZfG0sx7m/2jKkB4gscK0p7sNFjixFLSAz9OWOllpEkQLmCTDQKxOUErWA8Y5W7jbJgX/tVBotp4lkYseH9R5bvcRJT3ULIdwg5fB5JsOeD2SpyM/uwSUqdoU6womCpTap0+c5SKDQfDKtD7ngFYhNq7SE2eBEM8WE7i/XTooVKDEQUrLgPdCS0WC2nuhu3gMyImMczaxoCnpQjUuN/RjTiSEqb4Cu2KvqsD8oLOk21KS72r1T/t3N5F019/1c1MQ74p6kQSZsjZS9T2dc1X47CP8q4+XWp68Im1Bj2VRx4JUt/+lhbxwYffqZQf/8bh/Bf9ipVsHXUJJ9hhR+/0NzMuCL7V8uvO40xhwqZofDuB+K30y0faL1C74J1EhvQM/V5fK/wP2F1QcWFgbND0gkvjHj2eQoEf7nMn8GzwcY9Mw8I0bsiQRCsP5t1aeoaZW42hBeRxykX5HAafOmJSXwJ43bWMbgDl+LF6GfMm/lOHIYFRoPdXrgAlxo/8nizGBp7/ZOBWNaf9VMBAEhmMZkL7RiVj1BUBUr6R79Iyfy/5/4J2OE/7IBXukVA="
    # github
    # - secure: "J+1oWjvvXjyrwkY/4IFWKdN/weFmQcPwlRuFG4R0Gb3rYe4nqtC9l68sJvmS8asc8dQMhOhcUZCH6sjvo7l2WD4NuK4umPSbs+rJNUsfbvH4pZjStQIj/3ll1OfQelGDWAYQWhIfciYY4F3Bp0ZWTfKOppLQ2AVIYu1fPVXDdlo="
    # github changelog
    # - secure: "KcGydAqL7ryDh2rTJJB4wU8NE5BRtnrRXDEcPBScSscO3zFsHXHBDvvO04B/9hFVatXzGYXmkn+FZ0P9QikhvebzdwwyqUG2SKFiHhMvbX0m0WtAhn5NqDuKU1r5qy5YQ18r/tiLfC9GSAlEpfLAH58pwpcn8srV3Mn/yKvlrfs="

after_success:
  # this will short-circuit the publish step if it fails to interpolate $NPM_API_KEY
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"

deploy:
  provider: script
  script: scripts/release.sh
  skip_cleanup: true
  on:
    repo: Parity-JS/parity-react-app
    tags: false
